# Generated by Django 6.0.4 on 2026-05-05 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('imported_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'In attesa'), ('PROCESSING', 'In elaborazione'), ('COMPLETED', 'Completato'), ('FAILED', 'Fallito')], default='PENDING', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_batches',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('transaction_type', models.CharField(choices=[('Pagamento con carta', 'Pagamento con carta'), ('Pagamento', 'Pagamento'), ('Pagamento Revolut', 'Pagamento Revolut'), ('Ricarica', 'Ricarica'), ('Rimborso su carta', 'Rimborso su carta'), ('Prelievo', 'Prelievo'), ('Cambia valuta', 'Cambia valuta'), ('Addebita', 'Addebita')], max_length=30)),
                ('state', models.CharField(default='COMPLETATO', max_length=30)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='categories.category')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.importbatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user', 'completed_at'], name='transaction_user_id_7e98a6_idx'), models.Index(fields=['user', 'category'], name='transaction_user_id_738b85_idx'), models.Index(fields=['user', 'description'], name='transaction_user_id_c6bd61_idx')],
            },
        ),
    ]
