# Generated by Django 6.0.4 on 2026-05-06 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'In attesa'), ('PROCESSING', 'In elaborazione'), ('STAGED', 'Caricati in staging'), ('COMPLETED', 'Completato'), ('FAILED', 'Fallito')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='ImportStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('transaction_type', models.CharField(max_length=30)),
                ('state', models.CharField(default='COMPLETATO', max_length=30)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('row_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('is_error', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_transactions', to='transactions.importbatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_staging', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_staging',
                'indexes': [models.Index(fields=['user', 'import_batch'], name='import_stag_user_id_887fdc_idx'), models.Index(fields=['row_hash'], name='import_stag_row_has_0a419a_idx')],
            },
        ),
    ]
