# Generated by Django 6.0.5 on 2026-05-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='subscriptionoverride',
            new_name='subscriptio_user_id_0968ea_idx',
            old_name='subscriptio_user_id_4a1b9c_idx',
        ),
        migrations.RenameIndex(
            model_name='subscriptionoverride',
            new_name='subscriptio_user_id_636ca5_idx',
            old_name='subscriptio_user_id_4e52d6_idx',
        ),
    ]
